### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by SebouChu** [SebouChu/galerie_gbtlabsgjvjfavtr#5]
Voir **Updated version** en bas

**Comment by abaume** [comment]
Pour info, je me charge de : 
- ajouter un tag à un élément
- afficher les tags de l'élément

**Comment by jferreira40** [comment]
Je me charge maintenant de la suppression de tag

**Comment by SebouChu** [comment]
Updated : 

- [x] "Ajout d'un tag" à virer du front
- [x] "Suppression de tag" à virer du front
- [x] Page détails tag
  - [x] Component "Liste Albums" avec le tag 
  - [x] Component "Liste Photos" avec le tag
